Class {
	#name : #'A4BPUII18n_en',
	#superclass : #A4BPUII18n,
	#category : #'A4BP-View-I18n'
}

{ #category : #msg }
A4BPUII18n_en >> msgBPCopyName [
	^ 'Copy'
]

{ #category : #msg }
A4BPUII18n_en >> msgBPFromName [
	^ 'From'
]

{ #category : #msg }
A4BPUII18n_en >> msgBPSequenceName [
	^ 'Sequence'
]

{ #category : #msg }
A4BPUII18n_en >> msgBPToName [
	^ 'To'
]

{ #category : #msg }
A4BPUII18n_en >> msgBrowser [
	^ 'Browser'
]

{ #category : #msg }
A4BPUII18n_en >> msgDelete [
	^ 'Delete'
]

{ #category : #msgBPMN20 }
A4BPUII18n_en >> msgEndEvent [
	^ 'EndEvent'
]

{ #category : #msg }
A4BPUII18n_en >> msgInRoassal2Easel [
	^ 'In Roassal 2 Easel'
]

{ #category : #msg }
A4BPUII18n_en >> msgInRoassalEasel [
	^ 'In Roassal Easel'
]

{ #category : #msg }
A4BPUII18n_en >> msgInspect [
	^ 'Inspect'
]

{ #category : #msg }
A4BPUII18n_en >> msgInstrumentate [
	^ 'Instrument'
]

{ #category : #msg }
A4BPUII18n_en >> msgInstrumentations [
	^ 'Instrumentations'
]

{ #category : #msg }
A4BPUII18n_en >> msgModels [
	^ 'Models'
]

{ #category : #msg }
A4BPUII18n_en >> msgOpenNewSOAContext [
 ^ 'Open new SOA Context'
]

{ #category : #msg }
A4BPUII18n_en >> msgOpenView [
	^ 'Open view'
]

{ #category : #msg }
A4BPUII18n_en >> msgProcess [
	^ 'Process'
]

{ #category : #msg }
A4BPUII18n_en >> msgRelations [
	^ 'Relations'
]

{ #category : #msg }
A4BPUII18n_en >> msgSOAAnalyzerPanel [
 ^ 'SOA Analyzer Panel'
]

{ #category : #msg }
A4BPUII18n_en >> msgSOAModel [
 ^ 'SOA Model'
]

{ #category : #msg }
A4BPUII18n_en >> msgSOAModels [
 ^ 'SOA Models'
]

{ #category : #msg }
A4BPUII18n_en >> msgSource [
	^ 'Source'
]

{ #category : #msg }
A4BPUII18n_en >> msgSpy [
	^ 'Spy'
]

{ #category : #msgBPMN20 }
A4BPUII18n_en >> msgStartEvent [
	^ 'StartEvent'
]

{ #category : #msg }
A4BPUII18n_en >> msgStartInstrumentationListener [
	^ 'Start Listener'
]

{ #category : #msg }
A4BPUII18n_en >> msgVisualization [
	^ 'Visualization'
]
