Class {
	#name : #'A4BPUII18n_es',
	#superclass : #A4BPUII18n,
	#category : #'A4BP-View-I18n'
}

{ #category : #msg }
A4BPUII18n_es >> msgBPCopyName [
	^ 'Copiar'
]

{ #category : #msg }
A4BPUII18n_es >> msgBPFromName [
	^ 'Desde'
]

{ #category : #msg }
A4BPUII18n_es >> msgBPSequenceName [
	^ 'Secuencia'
]

{ #category : #msg }
A4BPUII18n_es >> msgBPToName [
	^ 'Para'
]

{ #category : #msg }
A4BPUII18n_es >> msgBrowser [
	^ 'Browser'
]

{ #category : #msg }
A4BPUII18n_es >> msgDelete [
	^ 'Eliminar'
]

{ #category : #msgBPMN20 }
A4BPUII18n_es >> msgEndEvent [
	^ 'EventoFin'
]

{ #category : #msg }
A4BPUII18n_es >> msgInRoassal2Easel [
	^ 'En Roassal 2 Easel'
]

{ #category : #msg }
A4BPUII18n_es >> msgInRoassalEasel [
	^ 'En Roassal Easel'
]

{ #category : #msg }
A4BPUII18n_es >> msgInspect [
	^ 'Inspeccionar'
]

{ #category : #msg }
A4BPUII18n_es >> msgInstrumentate [
	^ 'Instrumentar'
]

{ #category : #msg }
A4BPUII18n_es >> msgInstrumentations [
	^ 'Instrumentaciones'
]

{ #category : #msg }
A4BPUII18n_es >> msgModels [
	^ 'Modelos'
]

{ #category : #msg }
A4BPUII18n_es >> msgOpenNewSOAContext [
 ^ 'Abrir un nuevo contexto SOA'
]

{ #category : #msg }
A4BPUII18n_es >> msgOpenView [
	^ 'Abrir vista'
]

{ #category : #msg }
A4BPUII18n_es >> msgProcess [
	^ 'Procesos'
]

{ #category : #msg }
A4BPUII18n_es >> msgRelations [
	^ 'Relaciones'
]

{ #category : #msg }
A4BPUII18n_es >> msgSOAAnalyzerPanel [
 ^ 'Panel Analizador SOA'
]

{ #category : #msg }
A4BPUII18n_es >> msgSOAModel [
 ^ 'Modelo SOA'
]

{ #category : #msg }
A4BPUII18n_es >> msgSOAModels [
 ^ 'Modelos SOA'
]

{ #category : #msg }
A4BPUII18n_es >> msgSource [
	^ 'Fuente'
]

{ #category : #msg }
A4BPUII18n_es >> msgSpy [
	^ 'Spy'
]

{ #category : #msgBPMN20 }
A4BPUII18n_es >> msgStartEvent [
	^ 'EventoInicio'
]

{ #category : #msg }
A4BPUII18n_es >> msgStartInstrumentationListener [
	^ 'Iniciar Escuchador'
]

{ #category : #msg }
A4BPUII18n_es >> msgVisualization [
	^ 'Visualización'
]
