"
An A4BPBuilderSetNodesinBPScopeVisitor is xxxxxxxxx.

Instance Variables
	b:		<Object>

b
	- xxxxx

"
Class {
	#name : #A4BPBuilderSetNodesinBPScopeVisitor,
	#superclass : #A4BPBuildBPObjectCompositeVisitor,
	#instVars : [
		'b'
	],
	#category : #'A4BP-BPEL20-core-parser-builder'
}

{ #category : #'as yet unclassified' }
A4BPBuilderSetNodesinBPScopeVisitor class >> annotation [
<MSEClass: #A4BPBuilderSetNodesinBPScopeVisitor  super: #A4BPBuilderSetNodesinBPObjectCompositeVisitor >
<package: #'A4BP-BPEL20-core' >
]
