Class {
	#name : #BPEL20AbstractAssignBoundImpl,
	#superclass : #BPEL20Object,
	#instVars : [
		'property',
		'query',
		'part',
		'variable',
		'partnerLink',
		'expression'
	],
	#category : #'A4BP-BPEL20-core-model'
}

{ #category : #'as yet unclassified' }
BPEL20AbstractAssignBoundImpl class >> annotation [
<MSEClass: #BPEL20AbstractAssignBoundImpl  super: #BPEL20Object >
<package: #'A4BP-BPEL20-core' >
]

{ #category : #'as yet unclassified' }
BPEL20AbstractAssignBoundImpl >> expression [
^ expression
]

{ #category : #'as yet unclassified' }
BPEL20AbstractAssignBoundImpl >> expression: aexpression [
^ expression := aexpression
]

{ #category : #'as yet unclassified' }
BPEL20AbstractAssignBoundImpl >> part [
^ part
]

{ #category : #'as yet unclassified' }
BPEL20AbstractAssignBoundImpl >> part: apart [
^ part := apart
]

{ #category : #'as yet unclassified' }
BPEL20AbstractAssignBoundImpl >> partnerLink [
^ partnerLink
]

{ #category : #'as yet unclassified' }
BPEL20AbstractAssignBoundImpl >> partnerLink: apartnerLink [
^ partnerLink := apartnerLink
]

{ #category : #'as yet unclassified' }
BPEL20AbstractAssignBoundImpl >> property [
^ property
]

{ #category : #'as yet unclassified' }
BPEL20AbstractAssignBoundImpl >> property: aproperty [
^ property := aproperty
]

{ #category : #'as yet unclassified' }
BPEL20AbstractAssignBoundImpl >> query [
^ query
]

{ #category : #'as yet unclassified' }
BPEL20AbstractAssignBoundImpl >> query: aquery [
^ query := aquery
]

{ #category : #'as yet unclassified' }
BPEL20AbstractAssignBoundImpl >> variable [
^ variable
]

{ #category : #'as yet unclassified' }
BPEL20AbstractAssignBoundImpl >> variable: avariable [
^ variable := avariable
]
