Class {
	#name : #BPEL20CorrelationImpl,
	#superclass : #BPEL20BPELExtensibleElementImpl,
	#instVars : [
		'initiateESet',
		'pattern',
		'initiate',
		'set',
		'PATTERN_EDEFAULT',
		'INITIATE_EDEFAULT',
		'patternESet'
	],
	#category : #'A4BP-BPEL20-core-model'
}

{ #category : #'as yet unclassified' }
BPEL20CorrelationImpl class >> annotation [
<MSEClass: #BPEL20CorrelationImpl  super: #BPEL20BPELExtensibleElementImpl >
<package: #'A4BP-BPEL20-core' >
]

{ #category : #'as yet unclassified' }
BPEL20CorrelationImpl >> INITIATE_EDEFAULT [
^ INITIATE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20CorrelationImpl >> INITIATE_EDEFAULT: aINITIATE_EDEFAULT [
^ INITIATE_EDEFAULT := aINITIATE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20CorrelationImpl >> PATTERN_EDEFAULT [
^ PATTERN_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20CorrelationImpl >> PATTERN_EDEFAULT: aPATTERN_EDEFAULT [
^ PATTERN_EDEFAULT := aPATTERN_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20CorrelationImpl >> initiate [
^ initiate
]

{ #category : #'as yet unclassified' }
BPEL20CorrelationImpl >> initiate: ainitiate [
^ initiate := ainitiate
]

{ #category : #'as yet unclassified' }
BPEL20CorrelationImpl >> initiateESet [
^ initiateESet
]

{ #category : #'as yet unclassified' }
BPEL20CorrelationImpl >> initiateESet: ainitiateESet [
^ initiateESet := ainitiateESet
]

{ #category : #'as yet unclassified' }
BPEL20CorrelationImpl >> pattern [
^ pattern
]

{ #category : #'as yet unclassified' }
BPEL20CorrelationImpl >> pattern: apattern [
^ pattern := apattern
]

{ #category : #'as yet unclassified' }
BPEL20CorrelationImpl >> patternESet [
^ patternESet
]

{ #category : #'as yet unclassified' }
BPEL20CorrelationImpl >> patternESet: apatternESet [
^ patternESet := apatternESet
]

{ #category : #'as yet unclassified' }
BPEL20CorrelationImpl >> set [
^ set
]

{ #category : #'as yet unclassified' }
BPEL20CorrelationImpl >> set: aset [
^ set := aset
]
