Class {
	#name : #BPEL20Enum,
	#superclass : #A4BPObject,
	#category : #'A4BP-BPEL20-core-model'
}

{ #category : #'as yet unclassified' }
BPEL20Enum class >> annotation [
<MSEClass: #BPEL20Enum  super: #A4BPObject >
<package: #'A4BP-BPEL20-core' >
]

{ #category : #'as yet unclassified' }
BPEL20Enum >> childrens [
	^ childrens
]

{ #category : #'as yet unclassified' }
BPEL20Enum >> childrens: achildrens [
	^ childrens := achildrens
]

{ #category : #'as yet unclassified' }
BPEL20Enum >> myDocument [
	^ myDocument
]

{ #category : #'as yet unclassified' }
BPEL20Enum >> myDocument: amyDocument [
	^ myDocument := amyDocument
]

{ #category : #'as yet unclassified' }
BPEL20Enum >> parent [
	^ parent
]

{ #category : #'as yet unclassified' }
BPEL20Enum >> parent: aparent [
	^ parent := aparent
]

{ #category : #'as yet unclassified' }
BPEL20Enum >> state [
	^ state
]

{ #category : #'as yet unclassified' }
BPEL20Enum >> state: astate [
	^ state := astate
]

{ #category : #'as yet unclassified' }
BPEL20Enum >> text [
	^ text
]

{ #category : #'as yet unclassified' }
BPEL20Enum >> text: atext [
	^ text := atext
]
