Class {
	#name : #BPEL20AssignImpl,
	#superclass : #BPEL20ActivityImpl,
	#instVars : [
		'validate',
		'VALIDATE_EDEFAULT',
		'copy'
	],
	#category : #'A4BP-BPEL20-core-model'
}

{ #category : #'as yet unclassified' }
BPEL20AssignImpl class >> annotation [
<MSEClass: #BPEL20AssignImpl  super: #BPEL20ActivityImpl >
<package: #'A4BP-BPEL20-core' >
]

{ #category : #'as yet unclassified' }
BPEL20AssignImpl >> VALIDATE_EDEFAULT [
^ VALIDATE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20AssignImpl >> VALIDATE_EDEFAULT: aVALIDATE_EDEFAULT [
^ VALIDATE_EDEFAULT := aVALIDATE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20AssignImpl >> copy [
^ copy
]

{ #category : #'as yet unclassified' }
BPEL20AssignImpl >> copy: acopy [
^ copy := acopy
]

{ #category : #'as yet unclassified' }
BPEL20AssignImpl >> validate [
^ validate
]

{ #category : #'as yet unclassified' }
BPEL20AssignImpl >> validate: avalidate [
^ validate := avalidate
]
