Class {
	#name : #BPEL20ExpressionImpl,
	#superclass : #BPEL20Object,
	#instVars : [
		'opaque',
		'BODY_EDEFAULT',
		'opaqueESet',
		'EXPRESSION_LANGUAGE_EDEFAULT',
		'OPAQUE_EDEFAULT',
		'expressionLanguage',
		'body',
		'expressionLanguageESet'
	],
	#category : #'A4BP-BPEL20-core-model'
}

{ #category : #'as yet unclassified' }
BPEL20ExpressionImpl class >> annotation [
<MSEClass: #BPEL20ExpressionImpl  super: #BPEL20Object >
<package: #'A4BP-BPEL20-core' >
]

{ #category : #'as yet unclassified' }
BPEL20ExpressionImpl >> BODY_EDEFAULT [
^ BODY_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20ExpressionImpl >> BODY_EDEFAULT: aBODY_EDEFAULT [
^ BODY_EDEFAULT := aBODY_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20ExpressionImpl >> EXPRESSION_LANGUAGE_EDEFAULT [
^ EXPRESSION_LANGUAGE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20ExpressionImpl >> EXPRESSION_LANGUAGE_EDEFAULT: aEXPRESSION_LANGUAGE_EDEFAULT [
^ EXPRESSION_LANGUAGE_EDEFAULT := aEXPRESSION_LANGUAGE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20ExpressionImpl >> OPAQUE_EDEFAULT [
^ OPAQUE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20ExpressionImpl >> OPAQUE_EDEFAULT: aOPAQUE_EDEFAULT [
^ OPAQUE_EDEFAULT := aOPAQUE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20ExpressionImpl >> body [
^ body
]

{ #category : #'as yet unclassified' }
BPEL20ExpressionImpl >> body: abody [
^ body := abody
]

{ #category : #'as yet unclassified' }
BPEL20ExpressionImpl >> expressionLanguage [
^ expressionLanguage
]

{ #category : #'as yet unclassified' }
BPEL20ExpressionImpl >> expressionLanguage: aexpressionLanguage [
^ expressionLanguage := aexpressionLanguage
]

{ #category : #'as yet unclassified' }
BPEL20ExpressionImpl >> expressionLanguageESet [
^ expressionLanguageESet
]

{ #category : #'as yet unclassified' }
BPEL20ExpressionImpl >> expressionLanguageESet: aexpressionLanguageESet [
^ expressionLanguageESet := aexpressionLanguageESet
]

{ #category : #'as yet unclassified' }
BPEL20ExpressionImpl >> opaque [
^ opaque
]

{ #category : #'as yet unclassified' }
BPEL20ExpressionImpl >> opaque: aopaque [
^ opaque := aopaque
]

{ #category : #'as yet unclassified' }
BPEL20ExpressionImpl >> opaqueESet [
^ opaqueESet
]

{ #category : #'as yet unclassified' }
BPEL20ExpressionImpl >> opaqueESet: aopaqueESet [
^ opaqueESet := aopaqueESet
]
