Class {
	#name : #BPEL20BPELPackageImpl,
	#superclass : #BPEL20Object,
	#instVars : [
		'copyEClass',
		'messageExchangeEClass',
		'replyEClass',
		'onEventEClass',
		'abstractAssignBoundEClass',
		'correlationSetsEClass',
		'linksEClass',
		'linkEClass',
		'serviceRefEClass',
		'booleanExpressionEClass',
		'sourcesEClass',
		'messageExchangesEClass',
		'importEClass',
		'elseIfEClass',
		'processEClass',
		'documentationEClass',
		'toPartsEClass',
		'compensateScopeEClass',
		'faultHandlerEClass',
		'targetsEClass',
		'fromEClass',
		'isInited',
		'rethrowEClass',
		'whileEClass',
		'targetEClass',
		'toPartEClass',
		'expressionEClass',
		'terminationHandlerEClass',
		'extensionEClass',
		'endpointReferenceRoleEEnum',
		'branchesEClass',
		'completionConditionEClass',
		'compensationHandlerEClass',
		'correlationPatternEEnum',
		'exitEClass',
		'elseEClass',
		'extensionsEClass',
		'partnerActivityEClass',
		'partnerLinkEClass',
		'validateEClass',
		'flowEClass',
		'eventHandlerEClass',
		'emptyEClass',
		'correlationEClass',
		'activityEClass',
		'variableEClass',
		'forEachEClass',
		'queryEClass',
		'ifEClass',
		'bpelExtensibleElementEClass',
		'correlationSetEClass',
		'opaqueActivityEClass',
		'extensionActivityEClass',
		'unknownExtensibilityAttributeEClass',
		'invokeEClass',
		'compensateEClass',
		'scopeEClass',
		'isInitialized',
		'fromPartsEClass',
		'isCreated',
		'toEClass',
		'throwEClass',
		'sourceEClass',
		'pickEClass',
		'catchAllEClass',
		'partnerLinksEClass',
		'receiveEClass',
		'waitEClass',
		'assignEClass',
		'sequenceEClass',
		'variablesEClass',
		'conditionEClass',
		'correlationsEClass',
		'repeatUntilEClass',
		'onMessageEClass',
		'catchEClass',
		'fromPartEClass',
		'onAlarmEClass'
	],
	#category : #'A4BP-BPEL20-core-model'
}

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl class >> annotation [
<MSEClass: #BPEL20BPELPackageImpl  super: #BPEL20Object >
<package: #'A4BP-BPEL20-core' >
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> abstractAssignBoundEClass [
^ abstractAssignBoundEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> abstractAssignBoundEClass: aabstractAssignBoundEClass [
^ abstractAssignBoundEClass := aabstractAssignBoundEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> activityEClass [
^ activityEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> activityEClass: aactivityEClass [
^ activityEClass := aactivityEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> assignEClass [
^ assignEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> assignEClass: aassignEClass [
^ assignEClass := aassignEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> booleanExpressionEClass [
^ booleanExpressionEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> booleanExpressionEClass: abooleanExpressionEClass [
^ booleanExpressionEClass := abooleanExpressionEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> bpelExtensibleElementEClass [
^ bpelExtensibleElementEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> bpelExtensibleElementEClass: abpelExtensibleElementEClass [
^ bpelExtensibleElementEClass := abpelExtensibleElementEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> branchesEClass [
^ branchesEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> branchesEClass: abranchesEClass [
^ branchesEClass := abranchesEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> catchAllEClass [
^ catchAllEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> catchAllEClass: acatchAllEClass [
^ catchAllEClass := acatchAllEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> catchEClass [
^ catchEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> catchEClass: acatchEClass [
^ catchEClass := acatchEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> compensateEClass [
^ compensateEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> compensateEClass: acompensateEClass [
^ compensateEClass := acompensateEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> compensateScopeEClass [
^ compensateScopeEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> compensateScopeEClass: acompensateScopeEClass [
^ compensateScopeEClass := acompensateScopeEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> compensationHandlerEClass [
^ compensationHandlerEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> compensationHandlerEClass: acompensationHandlerEClass [
^ compensationHandlerEClass := acompensationHandlerEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> completionConditionEClass [
^ completionConditionEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> completionConditionEClass: acompletionConditionEClass [
^ completionConditionEClass := acompletionConditionEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> conditionEClass [
^ conditionEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> conditionEClass: aconditionEClass [
^ conditionEClass := aconditionEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> copyEClass [
^ copyEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> copyEClass: acopyEClass [
^ copyEClass := acopyEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> correlationEClass [
^ correlationEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> correlationEClass: acorrelationEClass [
^ correlationEClass := acorrelationEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> correlationPatternEEnum [
^ correlationPatternEEnum
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> correlationPatternEEnum: acorrelationPatternEEnum [
^ correlationPatternEEnum := acorrelationPatternEEnum
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> correlationSetEClass [
^ correlationSetEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> correlationSetEClass: acorrelationSetEClass [
^ correlationSetEClass := acorrelationSetEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> correlationSetsEClass [
^ correlationSetsEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> correlationSetsEClass: acorrelationSetsEClass [
^ correlationSetsEClass := acorrelationSetsEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> correlationsEClass [
^ correlationsEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> correlationsEClass: acorrelationsEClass [
^ correlationsEClass := acorrelationsEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> documentationEClass [
^ documentationEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> documentationEClass: adocumentationEClass [
^ documentationEClass := adocumentationEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> elseEClass [
^ elseEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> elseEClass: aelseEClass [
^ elseEClass := aelseEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> elseIfEClass [
^ elseIfEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> elseIfEClass: aelseIfEClass [
^ elseIfEClass := aelseIfEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> emptyEClass [
^ emptyEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> emptyEClass: aemptyEClass [
^ emptyEClass := aemptyEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> endpointReferenceRoleEEnum [
^ endpointReferenceRoleEEnum
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> endpointReferenceRoleEEnum: aendpointReferenceRoleEEnum [
^ endpointReferenceRoleEEnum := aendpointReferenceRoleEEnum
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> eventHandlerEClass [
^ eventHandlerEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> eventHandlerEClass: aeventHandlerEClass [
^ eventHandlerEClass := aeventHandlerEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> exitEClass [
^ exitEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> exitEClass: aexitEClass [
^ exitEClass := aexitEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> expressionEClass [
^ expressionEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> expressionEClass: aexpressionEClass [
^ expressionEClass := aexpressionEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> extensionActivityEClass [
^ extensionActivityEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> extensionActivityEClass: aextensionActivityEClass [
^ extensionActivityEClass := aextensionActivityEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> extensionEClass [
^ extensionEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> extensionEClass: aextensionEClass [
^ extensionEClass := aextensionEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> extensionsEClass [
^ extensionsEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> extensionsEClass: aextensionsEClass [
^ extensionsEClass := aextensionsEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> faultHandlerEClass [
^ faultHandlerEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> faultHandlerEClass: afaultHandlerEClass [
^ faultHandlerEClass := afaultHandlerEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> flowEClass [
^ flowEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> flowEClass: aflowEClass [
^ flowEClass := aflowEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> forEachEClass [
^ forEachEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> forEachEClass: aforEachEClass [
^ forEachEClass := aforEachEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> fromEClass [
^ fromEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> fromEClass: afromEClass [
^ fromEClass := afromEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> fromPartEClass [
^ fromPartEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> fromPartEClass: afromPartEClass [
^ fromPartEClass := afromPartEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> fromPartsEClass [
^ fromPartsEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> fromPartsEClass: afromPartsEClass [
^ fromPartsEClass := afromPartsEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> ifEClass [
^ ifEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> ifEClass: aifEClass [
^ ifEClass := aifEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> importEClass [
^ importEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> importEClass: aimportEClass [
^ importEClass := aimportEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> invokeEClass [
^ invokeEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> invokeEClass: ainvokeEClass [
^ invokeEClass := ainvokeEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> isCreated [
^ isCreated
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> isCreated: aisCreated [
^ isCreated := aisCreated
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> isInited [
^ isInited
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> isInited: aisInited [
^ isInited := aisInited
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> isInitialized [
^ isInitialized
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> isInitialized: aisInitialized [
^ isInitialized := aisInitialized
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> linkEClass [
^ linkEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> linkEClass: alinkEClass [
^ linkEClass := alinkEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> linksEClass [
^ linksEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> linksEClass: alinksEClass [
^ linksEClass := alinksEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> messageExchangeEClass [
^ messageExchangeEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> messageExchangeEClass: amessageExchangeEClass [
^ messageExchangeEClass := amessageExchangeEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> messageExchangesEClass [
^ messageExchangesEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> messageExchangesEClass: amessageExchangesEClass [
^ messageExchangesEClass := amessageExchangesEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> onAlarmEClass [
^ onAlarmEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> onAlarmEClass: aonAlarmEClass [
^ onAlarmEClass := aonAlarmEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> onEventEClass [
^ onEventEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> onEventEClass: aonEventEClass [
^ onEventEClass := aonEventEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> onMessageEClass [
^ onMessageEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> onMessageEClass: aonMessageEClass [
^ onMessageEClass := aonMessageEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> opaqueActivityEClass [
^ opaqueActivityEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> opaqueActivityEClass: aopaqueActivityEClass [
^ opaqueActivityEClass := aopaqueActivityEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> partnerActivityEClass [
^ partnerActivityEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> partnerActivityEClass: apartnerActivityEClass [
^ partnerActivityEClass := apartnerActivityEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> partnerLinkEClass [
^ partnerLinkEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> partnerLinkEClass: apartnerLinkEClass [
^ partnerLinkEClass := apartnerLinkEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> partnerLinksEClass [
^ partnerLinksEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> partnerLinksEClass: apartnerLinksEClass [
^ partnerLinksEClass := apartnerLinksEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> pickEClass [
^ pickEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> pickEClass: apickEClass [
^ pickEClass := apickEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> processEClass [
^ processEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> processEClass: aprocessEClass [
^ processEClass := aprocessEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> queryEClass [
^ queryEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> queryEClass: aqueryEClass [
^ queryEClass := aqueryEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> receiveEClass [
^ receiveEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> receiveEClass: areceiveEClass [
^ receiveEClass := areceiveEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> repeatUntilEClass [
^ repeatUntilEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> repeatUntilEClass: arepeatUntilEClass [
^ repeatUntilEClass := arepeatUntilEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> replyEClass [
^ replyEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> replyEClass: areplyEClass [
^ replyEClass := areplyEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> rethrowEClass [
^ rethrowEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> rethrowEClass: arethrowEClass [
^ rethrowEClass := arethrowEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> scopeEClass [
^ scopeEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> scopeEClass: ascopeEClass [
^ scopeEClass := ascopeEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> sequenceEClass [
^ sequenceEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> sequenceEClass: asequenceEClass [
^ sequenceEClass := asequenceEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> serviceRefEClass [
^ serviceRefEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> serviceRefEClass: aserviceRefEClass [
^ serviceRefEClass := aserviceRefEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> sourceEClass [
^ sourceEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> sourceEClass: asourceEClass [
^ sourceEClass := asourceEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> sourcesEClass [
^ sourcesEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> sourcesEClass: asourcesEClass [
^ sourcesEClass := asourcesEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> targetEClass [
^ targetEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> targetEClass: atargetEClass [
^ targetEClass := atargetEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> targetsEClass [
^ targetsEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> targetsEClass: atargetsEClass [
^ targetsEClass := atargetsEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> terminationHandlerEClass [
^ terminationHandlerEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> terminationHandlerEClass: aterminationHandlerEClass [
^ terminationHandlerEClass := aterminationHandlerEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> throwEClass [
^ throwEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> throwEClass: athrowEClass [
^ throwEClass := athrowEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> toEClass [
^ toEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> toEClass: atoEClass [
^ toEClass := atoEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> toPartEClass [
^ toPartEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> toPartEClass: atoPartEClass [
^ toPartEClass := atoPartEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> toPartsEClass [
^ toPartsEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> toPartsEClass: atoPartsEClass [
^ toPartsEClass := atoPartsEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> unknownExtensibilityAttributeEClass [
^ unknownExtensibilityAttributeEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> unknownExtensibilityAttributeEClass: aunknownExtensibilityAttributeEClass [
^ unknownExtensibilityAttributeEClass := aunknownExtensibilityAttributeEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> validateEClass [
^ validateEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> validateEClass: avalidateEClass [
^ validateEClass := avalidateEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> variableEClass [
^ variableEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> variableEClass: avariableEClass [
^ variableEClass := avariableEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> variablesEClass [
^ variablesEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> variablesEClass: avariablesEClass [
^ variablesEClass := avariablesEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> waitEClass [
^ waitEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> waitEClass: awaitEClass [
^ waitEClass := awaitEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> whileEClass [
^ whileEClass
]

{ #category : #'as yet unclassified' }
BPEL20BPELPackageImpl >> whileEClass: awhileEClass [
^ whileEClass := awhileEClass
]
