Class {
	#name : #BPEL20DocumentationImpl,
	#superclass : #BPEL20BPELExtensibleElementImpl,
	#instVars : [
		'LANG_EDEFAULT',
		'SOURCE_EDEFAULT',
		'source',
		'VALUE_EDEFAULT',
		'lang'
	],
	#category : #'A4BP-BPEL20-core-model'
}

{ #category : #'as yet unclassified' }
BPEL20DocumentationImpl class >> annotation [
<MSEClass: #BPEL20DocumentationImpl  super: #BPEL20BPELExtensibleElementImpl >
<package: #'A4BP-BPEL20-core' >
]

{ #category : #'as yet unclassified' }
BPEL20DocumentationImpl >> LANG_EDEFAULT [
^ LANG_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20DocumentationImpl >> LANG_EDEFAULT: aLANG_EDEFAULT [
^ LANG_EDEFAULT := aLANG_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20DocumentationImpl >> SOURCE_EDEFAULT [
^ SOURCE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20DocumentationImpl >> SOURCE_EDEFAULT: aSOURCE_EDEFAULT [
^ SOURCE_EDEFAULT := aSOURCE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20DocumentationImpl >> VALUE_EDEFAULT [
^ VALUE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20DocumentationImpl >> VALUE_EDEFAULT: aVALUE_EDEFAULT [
^ VALUE_EDEFAULT := aVALUE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20DocumentationImpl >> lang [
^ lang
]

{ #category : #'as yet unclassified' }
BPEL20DocumentationImpl >> lang: alang [
^ lang := alang
]

{ #category : #'as yet unclassified' }
BPEL20DocumentationImpl >> source [
^ source
]

{ #category : #'as yet unclassified' }
BPEL20DocumentationImpl >> source: asource [
^ source := asource
]
