Class {
	#name : #BPEL20ValidateImpl,
	#superclass : #BPEL20ActivityImpl,
	#instVars : [
		'variables'
	],
	#category : #'A4BP-BPEL20-core-model'
}

{ #category : #'as yet unclassified' }
BPEL20ValidateImpl class >> annotation [
<MSEClass: #BPEL20ValidateImpl  super: #BPEL20ActivityImpl >
<package: #'A4BP-BPEL20-core' >
]

{ #category : #'as yet unclassified' }
BPEL20ValidateImpl >> variables [
^ variables
]

{ #category : #'as yet unclassified' }
BPEL20ValidateImpl >> variables: avariables [
^ variables := avariables
]
