Class {
	#name : #BPEL20ToPartsImpl,
	#superclass : #BPEL20BPELExtensibleElementImpl,
	#instVars : [
		'children'
	],
	#category : #'A4BP-BPEL20-core-model'
}

{ #category : #'as yet unclassified' }
BPEL20ToPartsImpl class >> annotation [
<MSEClass: #BPEL20ToPartsImpl  super: #BPEL20BPELExtensibleElementImpl >
<package: #'A4BP-BPEL20-core' >
]

{ #category : #'as yet unclassified' }
BPEL20ToPartsImpl >> children [
^ children
]

{ #category : #'as yet unclassified' }
BPEL20ToPartsImpl >> children: achildren [
^ children := achildren
]
