Class {
	#name : #BPEL20CorrelationSetImpl,
	#superclass : #BPEL20BPELExtensibleElementImpl,
	#instVars : [
		'name',
		'NAME_EDEFAULT',
		'properties'
	],
	#category : #'A4BP-BPEL20-core-model'
}

{ #category : #'as yet unclassified' }
BPEL20CorrelationSetImpl class >> annotation [
<MSEClass: #BPEL20CorrelationSetImpl  super: #BPEL20BPELExtensibleElementImpl >
<package: #'A4BP-BPEL20-core' >
]

{ #category : #'as yet unclassified' }
BPEL20CorrelationSetImpl >> NAME_EDEFAULT [
^ NAME_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20CorrelationSetImpl >> NAME_EDEFAULT: aNAME_EDEFAULT [
^ NAME_EDEFAULT := aNAME_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20CorrelationSetImpl >> properties [
^ properties
]

{ #category : #'as yet unclassified' }
BPEL20CorrelationSetImpl >> properties: aproperties [
^ properties := aproperties
]
