Class {
	#name : #BPEL20ReceiveImpl,
	#superclass : #BPEL20PartnerActivityImpl,
	#instVars : [
		'createInstance',
		'createInstanceESet',
		'variable',
		'messageExchange',
		'CREATE_INSTANCE_EDEFAULT',
		'fromParts'
	],
	#category : #'A4BP-BPEL20-core-model'
}

{ #category : #'as yet unclassified' }
BPEL20ReceiveImpl class >> annotation [
<MSEClass: #BPEL20ReceiveImpl  super: #BPEL20PartnerActivityImpl >
<package: #'A4BP-BPEL20-core' >
]

{ #category : #'as yet unclassified' }
BPEL20ReceiveImpl >> CREATE_INSTANCE_EDEFAULT [
^ CREATE_INSTANCE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20ReceiveImpl >> CREATE_INSTANCE_EDEFAULT: aCREATE_INSTANCE_EDEFAULT [
^ CREATE_INSTANCE_EDEFAULT := aCREATE_INSTANCE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20ReceiveImpl >> createInstance [
^ createInstance
]

{ #category : #'as yet unclassified' }
BPEL20ReceiveImpl >> createInstance: acreateInstance [
^ createInstance := acreateInstance
]

{ #category : #'as yet unclassified' }
BPEL20ReceiveImpl >> createInstanceESet [
^ createInstanceESet
]

{ #category : #'as yet unclassified' }
BPEL20ReceiveImpl >> createInstanceESet: acreateInstanceESet [
^ createInstanceESet := acreateInstanceESet
]

{ #category : #'as yet unclassified' }
BPEL20ReceiveImpl >> fromParts [
^ fromParts
]

{ #category : #'as yet unclassified' }
BPEL20ReceiveImpl >> fromParts: afromParts [
^ fromParts := afromParts
]

{ #category : #'as yet unclassified' }
BPEL20ReceiveImpl >> messageExchange [
^ messageExchange
]

{ #category : #'as yet unclassified' }
BPEL20ReceiveImpl >> messageExchange: amessageExchange [
^ messageExchange := amessageExchange
]

{ #category : #'as yet unclassified' }
BPEL20ReceiveImpl >> variable [
^ variable
]

{ #category : #'as yet unclassified' }
BPEL20ReceiveImpl >> variable: avariable [
^ variable := avariable
]
