Class {
	#name : #BPEL20CorrelationSetsImpl,
	#superclass : #BPEL20BPELExtensibleElementImpl,
	#instVars : [
		'children'
	],
	#category : #'A4BP-BPEL20-core-model'
}

{ #category : #'as yet unclassified' }
BPEL20CorrelationSetsImpl class >> annotation [
<MSEClass: #BPEL20CorrelationSetsImpl  super: #BPEL20BPELExtensibleElementImpl >
<package: #'A4BP-BPEL20-core' >
]

{ #category : #'as yet unclassified' }
BPEL20CorrelationSetsImpl >> children [
^ children
]

{ #category : #'as yet unclassified' }
BPEL20CorrelationSetsImpl >> children: achildren [
^ children := achildren
]
