Class {
	#name : #BPEL20FromPartsImpl,
	#superclass : #BPEL20BPELExtensibleElementImpl,
	#instVars : [
		'children'
	],
	#category : #'A4BP-BPEL20-core-model'
}

{ #category : #'as yet unclassified' }
BPEL20FromPartsImpl class >> annotation [
<MSEClass: #BPEL20FromPartsImpl  super: #BPEL20BPELExtensibleElementImpl >
<package: #'A4BP-BPEL20-core' >
]

{ #category : #'as yet unclassified' }
BPEL20FromPartsImpl >> children [
^ children
]

{ #category : #'as yet unclassified' }
BPEL20FromPartsImpl >> children: achildren [
^ children := achildren
]
