Class {
	#name : #BPEL20PartnerLinkImpl,
	#superclass : #BPEL20BPELExtensibleElementImpl,
	#instVars : [
		'initializePartnerRole',
		'NAME_EDEFAULT',
		'name',
		'partnerLinkType',
		'partnerRole',
		'INITIALIZE_PARTNER_ROLE_EDEFAULT',
		'myRole',
		'initializePartnerRoleESet'
	],
	#category : #'A4BP-BPEL20-core-model'
}

{ #category : #'as yet unclassified' }
BPEL20PartnerLinkImpl class >> annotation [
<MSEClass: #BPEL20PartnerLinkImpl  super: #BPEL20BPELExtensibleElementImpl >
<package: #'A4BP-BPEL20-core' >
]

{ #category : #'as yet unclassified' }
BPEL20PartnerLinkImpl >> INITIALIZE_PARTNER_ROLE_EDEFAULT [
^ INITIALIZE_PARTNER_ROLE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20PartnerLinkImpl >> INITIALIZE_PARTNER_ROLE_EDEFAULT: aINITIALIZE_PARTNER_ROLE_EDEFAULT [
^ INITIALIZE_PARTNER_ROLE_EDEFAULT := aINITIALIZE_PARTNER_ROLE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20PartnerLinkImpl >> NAME_EDEFAULT [
^ NAME_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20PartnerLinkImpl >> NAME_EDEFAULT: aNAME_EDEFAULT [
^ NAME_EDEFAULT := aNAME_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPEL20PartnerLinkImpl >> initializePartnerRole [
^ initializePartnerRole
]

{ #category : #'as yet unclassified' }
BPEL20PartnerLinkImpl >> initializePartnerRole: ainitializePartnerRole [
^ initializePartnerRole := ainitializePartnerRole
]

{ #category : #'as yet unclassified' }
BPEL20PartnerLinkImpl >> initializePartnerRoleESet [
^ initializePartnerRoleESet
]

{ #category : #'as yet unclassified' }
BPEL20PartnerLinkImpl >> initializePartnerRoleESet: ainitializePartnerRoleESet [
^ initializePartnerRoleESet := ainitializePartnerRoleESet
]

{ #category : #'as yet unclassified' }
BPEL20PartnerLinkImpl >> myRole [
^ myRole
]

{ #category : #'as yet unclassified' }
BPEL20PartnerLinkImpl >> myRole: amyRole [
^ myRole := amyRole
]

{ #category : #'as yet unclassified' }
BPEL20PartnerLinkImpl >> partnerLinkType [
^ partnerLinkType
]

{ #category : #'as yet unclassified' }
BPEL20PartnerLinkImpl >> partnerLinkType: apartnerLinkType [
^ partnerLinkType := apartnerLinkType
]

{ #category : #'as yet unclassified' }
BPEL20PartnerLinkImpl >> partnerRole [
^ partnerRole
]

{ #category : #'as yet unclassified' }
BPEL20PartnerLinkImpl >> partnerRole: apartnerRole [
^ partnerRole := apartnerRole
]
