Class {
	#name : #BPEL20XSD2XMLGenerator,
	#superclass : #BPEL20Object,
	#instVars : [
		'BUILD_TEXT_NODES',
		'contentBuilder',
		'BUILD_OPTIONAL_ELEMENTS',
		'BUILD_ALL_CONTENT',
		'queryPath',
		'BUILD_ONLY_REQUIRED_CONTENT',
		'myBuildPolicy',
		'BUILD_STRUCTURE_ONLY',
		'BUILD_OPTIONAL_ATTRIBUTES',
		'xsdURI',
		'BUILD_FIRST_CHOICE',
		'BUILD_FIRST_SUBSTITUTION'
	],
	#category : #'A4BP-GenerateCode-BPEL20-org-eclipse-bpel-model-util'
}
