Class {
	#name : #BPEL20PropertyAliasImpl,
	#superclass : #BPEL20Object,
	#instVars : [
		'ID_EDEFAULT',
		'part',
		'wsdlPart',
		'XSD_ELEMENT_EDEFAULT',
		'query',
		'PROPERTY_NAME_EDEFAULT',
		'MESSAGE_TYPE_EDEFAULT',
		'messageType',
		'propertyName',
		'TYPE_EDEFAULT',
		'PART_EDEFAULT',
		'xsdElement',
		'type'
	],
	#category : #'A4BP-GenerateCode-BPEL20-org-eclipse-bpel-model-messageproperties-impl'
}
