Class {
	#name : #BPMN20Literals,
	#superclass : #Object,
	#instVars : [
		'POINT__Y',
		'DOCUMENT_ROOT__XSI_SCHEMA_LOCATION',
		'POINT',
		'BOUNDS__WIDTH',
		'FONT__SIZE',
		'DOCUMENT_ROOT',
		'BOUNDS__Y',
		'DOCUMENT_ROOT__BOUNDS',
		'DOCUMENT_ROOT__POINT',
		'BOUNDS__HEIGHT',
		'BOUNDS__X',
		'FONT__IS_ITALIC',
		'FONT__IS_BOLD',
		'FONT__IS_STRIKE_THROUGH',
		'POINT__X',
		'FONT',
		'FONT__IS_UNDERLINE',
		'DOCUMENT_ROOT__FONT',
		'DOCUMENT_ROOT__MIXED',
		'DOCUMENT_ROOT__XMLNS_PREFIX_MAP',
		'FONT__NAME',
		'BOUNDS'
	],
	#category : #'A4BP-GenerateCode-BPMN20-org-eclipse-dd-dc-DcPackage'
}
