Class {
	#name : #A4BPLog,
	#superclass : #Object,
	#category : #'A4BP-core-log'
}

{ #category : #'as yet unclassified' }
A4BPLog class >> annotation [
<MSEClass: #A4BPLog  super: #Object >
<package: #'A4BP-core' >
]

{ #category : #'as yet unclassified' }
A4BPLog class >> d: astring [
	Transcript
		show: astring;
		cr
]

{ #category : #'as yet unclassified' }
A4BPLog class >> e: astring [
	Transcript
		show: astring;
		cr
]

{ #category : #'as yet unclassified' }
A4BPLog class >> f: astring [
	Transcript
		show: astring;
		cr
]

{ #category : #'as yet unclassified' }
A4BPLog class >> l: astring [
	Transcript
		show: astring;
		cr
]

{ #category : #'as yet unclassified' }
A4BPLog class >> w: astring [
	Transcript
		show: astring;
		cr
]
