Class {
	#name : #BPSimObjectFactory,
	#superclass : #BPSimObject,
	#instVars : [
		'_ErlangDistribution_QNAME',
		'_DateTimeParameter_QNAME',
		'_LogNormalDistribution_QNAME',
		'_BooleanParameter_QNAME',
		'_BinomialDistribution_QNAME',
		'_FloatingParameter_QNAME',
		'_BetaDistribution_QNAME',
		'_EnumParameter_QNAME',
		'_DurationParameter_QNAME',
		'_TriangularDistribution_QNAME',
		'_NormalDistribution_QNAME',
		'_GammaDistribution_QNAME',
		'_PoissonDistribution_QNAME',
		'_WeibullDistribution_QNAME',
		'_NumericParameter_QNAME',
		'_ExpressionParameter_QNAME',
		'_StringParameter_QNAME',
		'_NegativeExponentialDistribution_QNAME',
		'_TruncatedNormalDistribution_QNAME',
		'_UserDistribution_QNAME',
		'_ParameterValue_QNAME',
		'_UniformDistribution_QNAME'
	],
	#category : #'A4BP-SimEngine-core-model'
}

{ #category : #'as yet unclassified' }
BPSimObjectFactory class >> annotation [
<MSEClass: #BPSimObjectFactory  super: #BPSimObject >
<package: #'A4BP-SimEngine-core' >
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory class >> fromXMLDescription: xmlDescription [
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _BetaDistribution_QNAME [
^ _BetaDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _BetaDistribution_QNAME: a_BetaDistribution_QNAME [
^ _BetaDistribution_QNAME := a_BetaDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _BinomialDistribution_QNAME [
^ _BinomialDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _BinomialDistribution_QNAME: a_BinomialDistribution_QNAME [
^ _BinomialDistribution_QNAME := a_BinomialDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _BooleanParameter_QNAME [
^ _BooleanParameter_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _BooleanParameter_QNAME: a_BooleanParameter_QNAME [
^ _BooleanParameter_QNAME := a_BooleanParameter_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _DateTimeParameter_QNAME [
^ _DateTimeParameter_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _DateTimeParameter_QNAME: a_DateTimeParameter_QNAME [
^ _DateTimeParameter_QNAME := a_DateTimeParameter_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _DurationParameter_QNAME [
^ _DurationParameter_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _DurationParameter_QNAME: a_DurationParameter_QNAME [
^ _DurationParameter_QNAME := a_DurationParameter_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _EnumParameter_QNAME [
^ _EnumParameter_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _EnumParameter_QNAME: a_EnumParameter_QNAME [
^ _EnumParameter_QNAME := a_EnumParameter_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _ErlangDistribution_QNAME [
^ _ErlangDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _ErlangDistribution_QNAME: a_ErlangDistribution_QNAME [
^ _ErlangDistribution_QNAME := a_ErlangDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _ExpressionParameter_QNAME [
^ _ExpressionParameter_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _ExpressionParameter_QNAME: a_ExpressionParameter_QNAME [
^ _ExpressionParameter_QNAME := a_ExpressionParameter_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _FloatingParameter_QNAME [
^ _FloatingParameter_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _FloatingParameter_QNAME: a_FloatingParameter_QNAME [
^ _FloatingParameter_QNAME := a_FloatingParameter_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _GammaDistribution_QNAME [
^ _GammaDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _GammaDistribution_QNAME: a_GammaDistribution_QNAME [
^ _GammaDistribution_QNAME := a_GammaDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _LogNormalDistribution_QNAME [
^ _LogNormalDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _LogNormalDistribution_QNAME: a_LogNormalDistribution_QNAME [
^ _LogNormalDistribution_QNAME := a_LogNormalDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _NegativeExponentialDistribution_QNAME [
^ _NegativeExponentialDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _NegativeExponentialDistribution_QNAME: a_NegativeExponentialDistribution_QNAME [
^ _NegativeExponentialDistribution_QNAME := a_NegativeExponentialDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _NormalDistribution_QNAME [
^ _NormalDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _NormalDistribution_QNAME: a_NormalDistribution_QNAME [
^ _NormalDistribution_QNAME := a_NormalDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _NumericParameter_QNAME [
^ _NumericParameter_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _NumericParameter_QNAME: a_NumericParameter_QNAME [
^ _NumericParameter_QNAME := a_NumericParameter_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _ParameterValue_QNAME [
^ _ParameterValue_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _ParameterValue_QNAME: a_ParameterValue_QNAME [
^ _ParameterValue_QNAME := a_ParameterValue_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _PoissonDistribution_QNAME [
^ _PoissonDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _PoissonDistribution_QNAME: a_PoissonDistribution_QNAME [
^ _PoissonDistribution_QNAME := a_PoissonDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _StringParameter_QNAME [
^ _StringParameter_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _StringParameter_QNAME: a_StringParameter_QNAME [
^ _StringParameter_QNAME := a_StringParameter_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _TriangularDistribution_QNAME [
^ _TriangularDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _TriangularDistribution_QNAME: a_TriangularDistribution_QNAME [
^ _TriangularDistribution_QNAME := a_TriangularDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _TruncatedNormalDistribution_QNAME [
^ _TruncatedNormalDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _TruncatedNormalDistribution_QNAME: a_TruncatedNormalDistribution_QNAME [
^ _TruncatedNormalDistribution_QNAME := a_TruncatedNormalDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _UniformDistribution_QNAME [
^ _UniformDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _UniformDistribution_QNAME: a_UniformDistribution_QNAME [
^ _UniformDistribution_QNAME := a_UniformDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _UserDistribution_QNAME [
^ _UserDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _UserDistribution_QNAME: a_UserDistribution_QNAME [
^ _UserDistribution_QNAME := a_UserDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _WeibullDistribution_QNAME [
^ _WeibullDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> _WeibullDistribution_QNAME: a_WeibullDistribution_QNAME [
^ _WeibullDistribution_QNAME := a_WeibullDistribution_QNAME
]

{ #category : #'as yet unclassified' }
BPSimObjectFactory >> accept: aVisitor [
	^ aVisitor visitBPSimObjectFactory: self
]
