Class {
	#name : #BPSimBPMN20RTEmptyObserver,
	#superclass : #Object,
	#category : #'A4BP-SimEngine-BPMN20-execution-observers'
}

{ #category : #'as yet unclassified' }
BPSimBPMN20RTEmptyObserver >> execution: anObject [
]

{ #category : #'as yet unclassified' }
BPSimBPMN20RTEmptyObserver >> makeView:  aview [
]

{ #category : #'as yet unclassified' }
BPSimBPMN20RTEmptyObserver >> notify: e [
]

{ #category : #'as yet unclassified' }
BPSimBPMN20RTEmptyObserver >> update [
]
