Extension { #name : #A4BPUnParserObj }

{ #category : #'*A4BP-BPMN20-core-model' }
A4BPUnParserObj >> flows [
	"return empty orderedcollection"

	^ OrderedCollection new
]

{ #category : #'*A4BP-BPMN20-core-model' }
A4BPUnParserObj >> inFlows [
	"return empty orderedcollection"

	^ OrderedCollection new
]

{ #category : #'*A4BP-BPMN20-core-model' }
A4BPUnParserObj >> outFlows [
	"return empty orderedcollection"

	^ OrderedCollection new
]

{ #category : #'*A4BP-BPMN20-core-model' }
A4BPUnParserObj >> shape [
	^ nil
]
