Class {
	#name : #BPMN20ParserSetinBPMN20ConditionalEventDefinitionImplVisitor,
	#superclass : #BPMN20ParserSetinBPMN20EventDefinitionImplVisitor,
	#category : #'A4BP-BPMN20-core-parser-builder-visitors'
}

{ #category : #'as yet unclassified' }
BPMN20ParserSetinBPMN20ConditionalEventDefinitionImplVisitor class >> annotation [
<MSEClass: #BPMN20ParserSetinBPMN20ConditionalEventDefinitionImplVisitor  super: #BPMN20ParserSetinBPMN20EventDefinitionImplVisitor >
<package: #'A4BP-BPMN20-core' >
]
