Class {
	#name : #BPMN20ParserSetinBPMN20ActivityImplVisitor,
	#superclass : #BPMN20ParserAbstractSetVisitor,
	#category : #'A4BP-BPMN20-core-parser-builder-visitors'
}

{ #category : #'as yet unclassified' }
BPMN20ParserSetinBPMN20ActivityImplVisitor class >> annotation [
<MSEClass: #BPMN20ParserSetinBPMN20ActivityImplVisitor  super: #BPMN20ParserAbstractSetVisitor >
<package: #'A4BP-BPMN20-core' >
]

{ #category : #visitor }
BPMN20ParserSetinBPMN20ActivityImplVisitor >> visitBPMN20LaneSetImpl: aModel [
]

{ #category : #visitor }
BPMN20ParserSetinBPMN20ActivityImplVisitor >> visitBPMN20ProcessImpl: aModel [
]
