Class {
	#name : #BPMN20ParserSetinBPMN20TaskImplVisitor,
	#superclass : #BPMN20ParserSetinBPMN20FlowNodeImplVisitor,
	#category : #'A4BP-BPMN20-core-parser-builder-visitors'
}

{ #category : #'as yet unclassified' }
BPMN20ParserSetinBPMN20TaskImplVisitor class >> annotation [
<MSEClass: #BPMN20ParserSetinBPMN20TaskImplVisitor  super: #BPMN20ParserSetinBPMN20FlowNodeImplVisitor >
<package: #'A4BP-BPMN20-core' >
]
