Class {
	#name : #BPMN20ParserSetinBPMN20ExtensionElementsImplVisitor,
	#superclass : #BPMN20ParserAbstractSetVisitor,
	#category : #'A4BP-BPMN20-core-parser-builder-visitors'
}

{ #category : #'as yet unclassified' }
BPMN20ParserSetinBPMN20ExtensionElementsImplVisitor class >> annotation [
<MSEClass: #BPMN20ParserSetinBPMN20ExtensionElementsImplVisitor  super: #BPMN20ParserAbstractSetVisitor >
<package: #'A4BP-BPMN20-core' >
]
