Class {
	#name : #BPMN20FormalExpressionImpl,
	#superclass : #BPMN20ExpressionImpl,
	#instVars : [
		'LANGUAGE_EDEFAULT',
		'evaluatesToTypeRef',
		'mixed',
		'language',
		'BODY_EDEFAULT'
	],
	#category : #'A4BP-BPMN20-core-model'
}

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl class >> annotation [
<MSEClass: #BPMN20FormalExpressionImpl  super: #BPMN20ExpressionImpl >
<package: #'A4BP-BPMN20-core' >
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> BODY_EDEFAULT [
^ BODY_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> BODY_EDEFAULT: aBODY_EDEFAULT [
^ BODY_EDEFAULT := aBODY_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> CANCEL_ACTIVITY_EDEFAULT [
	^ CANCEL_ACTIVITY_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> CANCEL_ACTIVITY_EDEFAULT: aCANCEL_ACTIVITY_EDEFAULT [
	^ CANCEL_ACTIVITY_EDEFAULT := aCANCEL_ACTIVITY_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> CANCEL_REMAINING_INSTANCES_EDEFAULT [
	^ CANCEL_REMAINING_INSTANCES_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> CANCEL_REMAINING_INSTANCES_EDEFAULT: aCANCEL_REMAINING_INSTANCES_EDEFAULT [
	^ CANCEL_REMAINING_INSTANCES_EDEFAULT := aCANCEL_REMAINING_INSTANCES_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> EVENT_GATEWAY_TYPE_EDEFAULT [
	^ EVENT_GATEWAY_TYPE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> EVENT_GATEWAY_TYPE_EDEFAULT: aEVENT_GATEWAY_TYPE_EDEFAULT [
	^ EVENT_GATEWAY_TYPE_EDEFAULT := aEVENT_GATEWAY_TYPE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> GATEWAY_DIRECTION_EDEFAULT [
	^ GATEWAY_DIRECTION_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> GATEWAY_DIRECTION_EDEFAULT: aGATEWAY_DIRECTION_EDEFAULT [
	^ GATEWAY_DIRECTION_EDEFAULT := aGATEWAY_DIRECTION_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> IMPLEMENTATION_EDEFAULT [
	^ IMPLEMENTATION_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> IMPLEMENTATION_EDEFAULT: aIMPLEMENTATION_EDEFAULT [
	^ IMPLEMENTATION_EDEFAULT := aIMPLEMENTATION_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> INSTANTIATE_EDEFAULT [
	^ INSTANTIATE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> INSTANTIATE_EDEFAULT: aINSTANTIATE_EDEFAULT [
	^ INSTANTIATE_EDEFAULT := aINSTANTIATE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> IS_COLLECTION_EDEFAULT [
	^ IS_COLLECTION_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> IS_COLLECTION_EDEFAULT: aIS_COLLECTION_EDEFAULT [
	^ IS_COLLECTION_EDEFAULT := aIS_COLLECTION_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> IS_IMMEDIATE_EDEFAULT [
	^ IS_IMMEDIATE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> IS_IMMEDIATE_EDEFAULT: aIS_IMMEDIATE_EDEFAULT [
	^ IS_IMMEDIATE_EDEFAULT := aIS_IMMEDIATE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> LANGUAGE_EDEFAULT [
^ LANGUAGE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> LANGUAGE_EDEFAULT: aLANGUAGE_EDEFAULT [
^ LANGUAGE_EDEFAULT := aLANGUAGE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> METHOD_EDEFAULT [
	^ METHOD_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> METHOD_EDEFAULT: aMETHOD_EDEFAULT [
	^ METHOD_EDEFAULT := aMETHOD_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> ORDERING_EDEFAULT [
	^ ORDERING_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> ORDERING_EDEFAULT: aORDERING_EDEFAULT [
	^ ORDERING_EDEFAULT := aORDERING_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> PARALLEL_MULTIPLE_EDEFAULT [
	^ PARALLEL_MULTIPLE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> PARALLEL_MULTIPLE_EDEFAULT: aPARALLEL_MULTIPLE_EDEFAULT [
	^ PARALLEL_MULTIPLE_EDEFAULT := aPARALLEL_MULTIPLE_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> PROTOCOL_EDEFAULT [
	^ PROTOCOL_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> PROTOCOL_EDEFAULT: aPROTOCOL_EDEFAULT [
	^ PROTOCOL_EDEFAULT := aPROTOCOL_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> SCRIPT_EDEFAULT [
	^ SCRIPT_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> SCRIPT_EDEFAULT: aSCRIPT_EDEFAULT [
	^ SCRIPT_EDEFAULT := aSCRIPT_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> SCRIPT_FORMAT_EDEFAULT [
	^ SCRIPT_FORMAT_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> SCRIPT_FORMAT_EDEFAULT: aSCRIPT_FORMAT_EDEFAULT [
	^ SCRIPT_FORMAT_EDEFAULT := aSCRIPT_FORMAT_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> TRIGGERED_BY_EVENT_EDEFAULT [
	^ TRIGGERED_BY_EVENT_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> TRIGGERED_BY_EVENT_EDEFAULT: aTRIGGERED_BY_EVENT_EDEFAULT [
	^ TRIGGERED_BY_EVENT_EDEFAULT := aTRIGGERED_BY_EVENT_EDEFAULT
]

{ #category : #visitor }
BPMN20FormalExpressionImpl >> accept: aVisitor [
	^ aVisitor visitBPMN20FormalExpressionImpl: self
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> activationCondition [
	^ activationCondition
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> activationCondition: aactivationCondition [
	^ activationCondition := aactivationCondition
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> anyAttribute [
	^ anyAttribute
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> anyAttribute: aanyAttribute [
	^ anyAttribute := aanyAttribute
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> artifacts [
	^ artifacts
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> artifacts: aartifacts [
	^ artifacts := aartifacts
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> attachedToRef [
	^ attachedToRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> attachedToRef: aattachedToRef [
	^ attachedToRef := aattachedToRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> auditing [
	^ auditing
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> auditing: aauditing [
	^ auditing := aauditing
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> boundaryEventRefs [
	^ boundaryEventRefs
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> boundaryEventRefs: aboundaryEventRefs [
	^ boundaryEventRefs := aboundaryEventRefs
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> calledChoreographyRef [
	^ calledChoreographyRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> calledChoreographyRef: acalledChoreographyRef [
	^ calledChoreographyRef := acalledChoreographyRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> calledElementRef [
	^ calledElementRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> calledElementRef: acalledElementRef [
	^ calledElementRef := acalledElementRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> cancelActivity [
	^ cancelActivity
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> cancelActivity: acancelActivity [
	^ cancelActivity := acancelActivity
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> cancelRemainingInstances [
	^ cancelRemainingInstances
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> cancelRemainingInstances: acancelRemainingInstances [
	^ cancelRemainingInstances := acancelRemainingInstances
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> categoryValueRef [
	^ categoryValueRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> categoryValueRef: acategoryValueRef [
	^ categoryValueRef := acategoryValueRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> completionCondition [
	^ completionCondition
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> completionCondition: acompletionCondition [
	^ completionCondition := acompletionCondition
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> completionQuantity [
	^ completionQuantity
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> completionQuantity: acompletionQuantity [
	^ completionQuantity := acompletionQuantity
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> conditionExpression [
	^ conditionExpression
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> conditionExpression: aconditionExpression [
	^ conditionExpression := aconditionExpression
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> correlationKeys [
	^ correlationKeys
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> correlationKeys: acorrelationKeys [
	^ correlationKeys := acorrelationKeys
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> dataInputAssociation [
	^ dataInputAssociation
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> dataInputAssociation: adataInputAssociation [
	^ dataInputAssociation := adataInputAssociation
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> dataInputAssociations [
	^ dataInputAssociations
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> dataInputAssociations: adataInputAssociations [
	^ dataInputAssociations := adataInputAssociations
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> dataInputs [
	^ dataInputs
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> dataInputs: adataInputs [
	^ dataInputs := adataInputs
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> dataObjectRef [
	^ dataObjectRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> dataObjectRef: adataObjectRef [
	^ dataObjectRef := adataObjectRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> dataOutputAssociation [
	^ dataOutputAssociation
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> dataOutputAssociation: adataOutputAssociation [
	^ dataOutputAssociation := adataOutputAssociation
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> dataOutputAssociations [
	^ dataOutputAssociations
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> dataOutputAssociations: adataOutputAssociations [
	^ dataOutputAssociations := adataOutputAssociations
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> dataOutputs [
	^ dataOutputs
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> dataOutputs: adataOutputs [
	^ dataOutputs := adataOutputs
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> dataState [
	^ dataState
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> dataState: adataState [
	^ dataState := adataState
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> dataStoreRef [
	^ dataStoreRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> dataStoreRef: adataStoreRef [
	^ dataStoreRef := adataStoreRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> default_ [
	^ default_
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> default_: adefault_ [
	^ default_ := adefault_
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> documentation [
	^ documentation
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> documentation: adocumentation [
	^ documentation := adocumentation
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> evaluatesToTypeRef [
^ evaluatesToTypeRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> evaluatesToTypeRef: aevaluatesToTypeRef [
^ evaluatesToTypeRef := aevaluatesToTypeRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> eventDefinitionRefs [
	^ eventDefinitionRefs
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> eventDefinitionRefs: aeventDefinitionRefs [
	^ eventDefinitionRefs := aeventDefinitionRefs
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> eventDefinitions [
	^ eventDefinitions
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> eventDefinitions: aeventDefinitions [
	^ eventDefinitions := aeventDefinitions
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> eventGatewayType [
	^ eventGatewayType
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> eventGatewayType: aeventGatewayType [
	^ eventGatewayType := aeventGatewayType
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> extensionDefinitions [
	^ extensionDefinitions
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> extensionDefinitions: aextensionDefinitions [
	^ extensionDefinitions := aextensionDefinitions
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> extensionValues [
	^ extensionValues
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> extensionValues: aextensionValues [
	^ extensionValues := aextensionValues
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> flowElements [
	^ flowElements
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> flowElements: aflowElements [
	^ flowElements := aflowElements
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> gatewayDirection [
	^ gatewayDirection
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> gatewayDirection: agatewayDirection [
	^ gatewayDirection := agatewayDirection
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> implementation [
	^ implementation
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> implementation: aimplementation [
	^ implementation := aimplementation
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> incoming [
	^ incoming
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> incoming: aincoming [
	^ incoming := aincoming
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> initiatingParticipantRef [
	^ initiatingParticipantRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> initiatingParticipantRef: ainitiatingParticipantRef [
	^ initiatingParticipantRef := ainitiatingParticipantRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> inputSet [
	^ inputSet
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> inputSet: ainputSet [
	^ inputSet := ainputSet
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> instantiate [
	^ instantiate
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> instantiate: ainstantiate [
	^ instantiate := ainstantiate
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> ioSpecification [
	^ ioSpecification
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> ioSpecification: aioSpecification [
	^ ioSpecification := aioSpecification
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> isCollection [
	^ isCollection
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> isCollection: aisCollection [
	^ isCollection := aisCollection
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> isForCompensation [
	^ isForCompensation
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> isForCompensation: aisForCompensation [
	^ isForCompensation := aisForCompensation
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> isImmediate [
	^ isImmediate
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> isImmediate: aisImmediate [
	^ isImmediate := aisImmediate
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> isInterrupting [
	^ isInterrupting
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> isInterrupting: aisInterrupting [
	^ isInterrupting := aisInterrupting
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> itemSubjectRef [
	^ itemSubjectRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> itemSubjectRef: aitemSubjectRef [
	^ itemSubjectRef := aitemSubjectRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> laneSets [
	^ laneSets
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> laneSets: alaneSets [
	^ laneSets := alaneSets
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> lanes [
	^ lanes
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> lanes: alanes [
	^ lanes := alanes
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> language [
^ language
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> language: alanguage [
^ language := alanguage
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> loopCharacteristics [
	^ loopCharacteristics
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> loopCharacteristics: aloopCharacteristics [
	^ loopCharacteristics := aloopCharacteristics
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> loopType [
	^ loopType
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> loopType: aloopType [
	^ loopType := aloopType
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> messageFlowRef [
	^ messageFlowRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> messageFlowRef: amessageFlowRef [
	^ messageFlowRef := amessageFlowRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> messageRef [
	^ messageRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> messageRef: amessageRef [
	^ messageRef := amessageRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> method [
	^ method
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> method: amethod [
	^ method := amethod
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> mixed [
^ mixed
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> mixed: amixed [
^ mixed := amixed
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> monitoring [
	^ monitoring
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> monitoring: amonitoring [
	^ monitoring := amonitoring
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> myDocument [
	^ myDocument
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> myDocument: amyDocument [
	^ myDocument := amyDocument
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> operationRef [
	^ operationRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> operationRef: aoperationRef [
	^ operationRef := aoperationRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> ordering [
	^ ordering
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> ordering: aordering [
	^ ordering := aordering
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> outgoing [
	^ outgoing
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> outgoing: aoutgoing [
	^ outgoing := aoutgoing
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> outputSet [
	^ outputSet
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> outputSet: aoutputSet [
	^ outputSet := aoutputSet
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> parallelMultiple [
	^ parallelMultiple
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> parallelMultiple: aparallelMultiple [
	^ parallelMultiple := aparallelMultiple
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> participantAssociations [
	^ participantAssociations
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> participantAssociations: aparticipantAssociations [
	^ participantAssociations := aparticipantAssociations
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> participantRefs [
	^ participantRefs
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> participantRefs: aparticipantRefs [
	^ participantRefs := aparticipantRefs
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> properties [
	^ properties
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> properties: aproperties [
	^ properties := aproperties
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> protocol [
	^ protocol
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> protocol: aprotocol [
	^ protocol := aprotocol
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> renderings [
	^ renderings
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> renderings: arenderings [
	^ renderings := arenderings
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> resources [
	^ resources
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> resources: aresources [
	^ resources := aresources
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> script [
	^ script
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> script: ascript [
	^ script := ascript
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> scriptFormat [
	^ scriptFormat
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> scriptFormat: ascriptFormat [
	^ scriptFormat := ascriptFormat
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> sourceRef [
	^ sourceRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> sourceRef: asourceRef [
	^ sourceRef := asourceRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> startQuantity [
	^ startQuantity
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> startQuantity: astartQuantity [
	^ startQuantity := astartQuantity
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> state [
	^ state
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> state: astate [
	^ state := astate
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> targetRef [
	^ targetRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> targetRef: atargetRef [
	^ targetRef := atargetRef
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> text [
	^ text
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> text: atext [
	^ text := atext
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> triggeredByEvent [
	^ triggeredByEvent
]

{ #category : #'as yet unclassified' }
BPMN20FormalExpressionImpl >> triggeredByEvent: atriggeredByEvent [
	^ triggeredByEvent := atriggeredByEvent
]
