Class {
	#name : #BPMN20ParserSetinBPMN20InterfaceImplVisitor,
	#superclass : #BPMN20ParserSetinBPMN20RootElementImplVisitor,
	#category : #'A4BP-BPMN20-core-parser-builder-visitors'
}

{ #category : #'as yet unclassified' }
BPMN20ParserSetinBPMN20InterfaceImplVisitor class >> annotation [
<MSEClass: #BPMN20ParserSetinBPMN20InterfaceImplVisitor  super: #BPMN20ParserSetinBPMN20RootElementImplVisitor >
<package: #'A4BP-BPMN20-core' >
]
