Class {
	#name : #BPMN20ParserSetinBPMN20GlobalChoreographyTaskImplVisitor,
	#superclass : #BPMN20ParserSetinBPMN20CollaborationImplVisitor,
	#category : #'A4BP-BPMN20-core-parser-builder-visitors'
}

{ #category : #'as yet unclassified' }
BPMN20ParserSetinBPMN20GlobalChoreographyTaskImplVisitor class >> annotation [
<MSEClass: #BPMN20ParserSetinBPMN20GlobalChoreographyTaskImplVisitor  super: #BPMN20ParserSetinBPMN20CollaborationImplVisitor >
<package: #'A4BP-BPMN20-core' >
]
