Class {
	#name : #BPMN20ParserSetinBPMN20GlobalTaskImplVisitor,
	#superclass : #BPMN20ParserSetinBPMN20CallableElementImplVisitor,
	#category : #'A4BP-BPMN20-core-parser-builder-visitors'
}

{ #category : #'as yet unclassified' }
BPMN20ParserSetinBPMN20GlobalTaskImplVisitor class >> annotation [
<MSEClass: #BPMN20ParserSetinBPMN20GlobalTaskImplVisitor  super: #BPMN20ParserSetinBPMN20CallableElementImplVisitor >
<package: #'A4BP-BPMN20-core' >
]
