Class {
	#name : #BPMN20ParserSetinBPMN20BoundaryEventImplVisitor,
	#superclass : #BPMN20ParserSetinBPMN20CatchEventImplVisitor,
	#category : #'A4BP-BPMN20-core-parser-builder-visitors'
}

{ #category : #'as yet unclassified' }
BPMN20ParserSetinBPMN20BoundaryEventImplVisitor class >> annotation [
<MSEClass: #BPMN20ParserSetinBPMN20BoundaryEventImplVisitor  super: #BPMN20ParserSetinBPMN20CatchEventImplVisitor >
<package: #'A4BP-BPMN20-core' >
]
