Class {
	#name : #BPMN20ParserSetinBPMN20ThrowEventImplVisitor,
	#superclass : #BPMN20ParserSetinBPMN20EventImplVisitor,
	#category : #'A4BP-BPMN20-core-parser-builder-visitors'
}

{ #category : #'as yet unclassified' }
BPMN20ParserSetinBPMN20ThrowEventImplVisitor class >> annotation [
<MSEClass: #BPMN20ParserSetinBPMN20ThrowEventImplVisitor  super: #BPMN20ParserSetinBPMN20EventImplVisitor >
<package: #'A4BP-BPMN20-core' >
]
