Class {
	#name : #BPMN20ParserSetinBPMN20RefToBeBuildImplVisitor,
	#superclass : #BPMN20ParserAbstractSetVisitor,
	#category : #'A4BP-BPMN20-core-parser-builder-visitors'
}

{ #category : #'as yet unclassified' }
BPMN20ParserSetinBPMN20RefToBeBuildImplVisitor class >> annotation [
<MSEClass: #BPMN20ParserSetinBPMN20RefToBeBuildImplVisitor  super: #BPMN20ParserAbstractSetVisitor >
<package: #'A4BP-BPMN20-core' >
]

{ #category : #visitor }
BPMN20ParserSetinBPMN20RefToBeBuildImplVisitor >> visitBPMN20FlowNodeImpl: aModel [
	"do nothing"
]

{ #category : #visitor }
BPMN20ParserSetinBPMN20RefToBeBuildImplVisitor >> visitBPMN20LaneSetImpl: aModel [
	"do nothing"
]

{ #category : #visitor }
BPMN20ParserSetinBPMN20RefToBeBuildImplVisitor >> visitBPMN20ProcessImpl: aModel [
	"do nothing"

	
]
