Class {
	#name : #BPMN20ParserSetinBPMN20FlowNodeRefImplVisitor,
	#superclass : #BPMN20ParserSetinBPMN20RefToBeBuildImplVisitor,
	#category : #'A4BP-BPMN20-core-parser-builder-visitors'
}

{ #category : #'as yet unclassified' }
BPMN20ParserSetinBPMN20FlowNodeRefImplVisitor class >> annotation [
<MSEClass: #BPMN20ParserSetinBPMN20FlowNodeRefImplVisitor  super: #BPMN20ParserSetinBPMN20RefToBeBuildImplVisitor >
<package: #'A4BP-BPMN20-core' >
]
