Class {
	#name : #BPMN20ParserSetinBPMN20GlobalScriptTaskImplVisitor,
	#superclass : #BPMN20ParserSetinBPMN20GlobalTaskImplVisitor,
	#category : #'A4BP-BPMN20-core-parser-builder-visitors'
}

{ #category : #'as yet unclassified' }
BPMN20ParserSetinBPMN20GlobalScriptTaskImplVisitor class >> annotation [
<MSEClass: #BPMN20ParserSetinBPMN20GlobalScriptTaskImplVisitor  super: #BPMN20ParserSetinBPMN20GlobalTaskImplVisitor >
<package: #'A4BP-BPMN20-core' >
]
