Class {
	#name : #BPMN20GlobalBusinessRuleTaskImpl,
	#superclass : #BPMN20GlobalTaskImpl,
	#instVars : [
		'IMPLEMENTATION_EDEFAULT',
		'implementation'
	],
	#category : #'A4BP-BPMN20-core-model'
}

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl class >> annotation [
<MSEClass: #BPMN20GlobalBusinessRuleTaskImpl  super: #BPMN20GlobalTaskImpl >
<package: #'A4BP-BPMN20-core' >
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> IMPLEMENTATION_EDEFAULT [
^ IMPLEMENTATION_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> IMPLEMENTATION_EDEFAULT: aIMPLEMENTATION_EDEFAULT [
^ IMPLEMENTATION_EDEFAULT := aIMPLEMENTATION_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> NAME_EDEFAULT [
	^ NAME_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> NAME_EDEFAULT: aNAME_EDEFAULT [
	^ NAME_EDEFAULT := aNAME_EDEFAULT
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> accept: aVisitor [
	^ aVisitor visitBPMN20GlobalBusinessRuleTaskImpl: self
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> anyAttribute [
	^ anyAttribute
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> anyAttribute: aanyAttribute [
	^ anyAttribute := aanyAttribute
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> documentation [
	^ documentation
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> documentation: adocumentation [
	^ documentation := adocumentation
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> extensionDefinitions [
	^ extensionDefinitions
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> extensionDefinitions: aextensionDefinitions [
	^ extensionDefinitions := aextensionDefinitions
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> extensionValues [
	^ extensionValues
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> extensionValues: aextensionValues [
	^ extensionValues := aextensionValues
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> implementation [
^ implementation
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> implementation: aimplementation [
^ implementation := aimplementation
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> ioBinding [
	^ ioBinding
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> ioBinding: aioBinding [
	^ ioBinding := aioBinding
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> ioSpecification [
	^ ioSpecification
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> ioSpecification: aioSpecification [
	^ ioSpecification := aioSpecification
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> myDocument [
	^ myDocument
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> myDocument: amyDocument [
	^ myDocument := amyDocument
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> resources [
	^ resources
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> resources: aresources [
	^ resources := aresources
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> state [
	^ state
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> state: astate [
	^ state := astate
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> supportedInterfaceRefs [
	^ supportedInterfaceRefs
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> supportedInterfaceRefs: asupportedInterfaceRefs [
	^ supportedInterfaceRefs := asupportedInterfaceRefs
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> text [
	^ text
]

{ #category : #'as yet unclassified' }
BPMN20GlobalBusinessRuleTaskImpl >> text: atext [
	^ text := atext
]
