Class {
	#name : #BPMN20DiParserDiagramElementImplVisitor,
	#superclass : #BPMN20DiParserAbstractSetVisitor,
	#category : #'A4BP-BPMN20-core-parser-builder-visitors-di'
}

{ #category : #'as yet unclassified' }
BPMN20DiParserDiagramElementImplVisitor class >> annotation [
<MSEClass: #BPMN20DiParserDiagramElementImplVisitor  super: #BPMN20DiParserAbstractSetVisitor >
<package: #'A4BP-BPMN20-core' >
]
