Class {
	#name : #BPMN20ParserSetinBPMN20ImplicitThrowEventImplVisitor,
	#superclass : #BPMN20ParserSetinBPMN20ThrowEventImplVisitor,
	#category : #'A4BP-BPMN20-core-parser-builder-visitors'
}

{ #category : #'as yet unclassified' }
BPMN20ParserSetinBPMN20ImplicitThrowEventImplVisitor class >> annotation [
<MSEClass: #BPMN20ParserSetinBPMN20ImplicitThrowEventImplVisitor  super: #BPMN20ParserSetinBPMN20ThrowEventImplVisitor >
<package: #'A4BP-BPMN20-core' >
]
