"
A BPActivityStructured is a inheritance structure of activities than contain other activities.


Structured activities are those activities which can contain other activities.
"
Class {
	#name : #BPActivityStructured,
	#superclass : #BPActivity,
	#category : #'A4BP-BpelAnalyzer-core-model-bpel'
}

{ #category : #'as yet unclassified' }
BPActivityStructured class >> annotation [
<MSEClass: #BPActivityStructured  super: #BPActivity >
<package: #'A4BP-BpelAnalyzer-core' >
]

{ #category : #initialization }
BPActivityStructured >> initialize [
	super initialize.
]
