Class {
	#name : #BpelExampleTest,
	#superclass : #TestCase,
	#category : #'A4BP-BpelAnalyzer-core-example'
}

{ #category : #'as yet unclassified' }
BpelExampleTest >> testBPVCSOAContextProcessCFC [
]

{ #category : #'as yet unclassified' }
BpelExampleTest >> testBPVCSOAContextSimple [
]

{ #category : #'as yet unclassified' }
BpelExampleTest >> testCFC_example01_bankLoanProcessV001 [
]

{ #category : #'as yet unclassified' }
BpelExampleTest >> testexample01 [
]

{ #category : #'as yet unclassified' }
BpelExampleTest >> testexample02 [
]

{ #category : #'as yet unclassified' }
BpelExampleTest >> testexample03 [
]

{ #category : #'as yet unclassified' }
BpelExampleTest >> testexample04 [
]

{ #category : #'as yet unclassified' }
BpelExampleTest >> testexample05 [
]

{ #category : #'as yet unclassified' }
BpelExampleTest >> testexample06 [
]

{ #category : #'as yet unclassified' }
BpelExampleTest >> testexample07 [
]

{ #category : #'as yet unclassified' }
BpelExampleTest >> testexample08 [
]

{ #category : #'as yet unclassified' }
BpelExampleTest >> testexample09 [
]

{ #category : #'as yet unclassified' }
BpelExampleTest >> testexample10 [
]
