"
A BPOnAlarmEvent is xxxxxxxxx.

Instance Variables
	bpForUntilGroup:		<Object>
	bpRepeatEvery:		<Object>

bpForUntilGroup
	- xxxxx

bpRepeatEvery
	- xxxxx

"
Class {
	#name : #BPOnAlarmEvent,
	#superclass : #BPBPELObject,
	#instVars : [
		'bpForUntilGroup',
		'bpRepeatEvery'
	],
	#category : #'A4BP-BpelAnalyzer-core-model-bpel'
}

{ #category : #'as yet unclassified' }
BPOnAlarmEvent class >> annotation [
<MSEClass: #BPOnAlarmEvent  super: #BPBPELObject >
<package: #'A4BP-BpelAnalyzer-core' >
]
